server:
  port: 8080


spring:
  redis:
    database: 0
    host: tlshop.com
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 10000

